from __future__ import annotations
import io
import zipfile
from typing import TYPE_CHECKING, Dict, Union, Any

if TYPE_CHECKING:
    from ....models.esdm_models import Workbook
    from ..base import ESDMBaseWriter
    from .extra_writers import ContentTypesWriter, RelationshipsWriter


class ZipPackager:
    def __init__(self, parent_writer: ESDMBaseWriter):
        self._parent = parent_writer

    async def pack(
        self,
        workbook: Workbook,
        parts: Dict[str, Union[str, bytes]],
        content_types_writer: ContentTypesWriter,
        rels_writer: RelationshipsWriter,
    ) -> bytes:
        with io.BytesIO() as buffer:
            with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
                for path, content in parts.items():
                    if isinstance(content, str):
                        content = content.encode('utf-8')
                    zf.writestr(path, content)
                self._add_extra_parts(zf)

                types_xml = content_types_writer.write(workbook)
                zf.writestr('[Content_Types].xml', types_xml.encode('utf-8'))
                rels_xml = rels_writer.write_root_rels(workbook)
                zf.writestr('_rels/.rels', rels_xml.encode('utf-8'))
                self._add_image_binaries(zf)
            return buffer.getvalue()

    def _add_extra_parts(self, zf: zipfile.ZipFile):
        """Add extra parts that were generated by sub-writers (e.g., VML drawings, extra XMLs)."""
        if hasattr(self._parent, '_extra_parts'):
            for path, content in self._parent._extra_parts.items():
                if isinstance(content, str):
                    content = content.encode('utf-8')
                zf.writestr(path, content)

    def _add_image_binaries(self, zf: zipfile.ZipFile):
        """Add image binaries stored in the parent writer's _image_binaries dict."""
        if hasattr(self._parent, '_image_binaries'):
            for path, binary in self._parent._image_binaries.items():
                if binary:  # only write if binary data exists
                    zf.writestr(path, binary)