from .conftest import TestAgent, TestRegistry, DummyMessageBus1, registry, message_bus, make_agent
from .test_autogen_interaction_backend import DummyRegistry1, DummyMessageBus2, DummyResult, SimpleRequest, test_autogen_falls_back_to_native_note, test_autogen_keeps_wrapper_note_when_available
from .test_broadcast_strategy import test_broadcast_merge_mode, test_broadcast_vote_mode_ignores_non_string
from .test_coordinator_strategy import test_coordinator_strategy_runs_workers_and_aggregates, test_coordinator_strategy_captures_worker_errors
from .test_debate_strategy import test_debate_finishes_when_critic_approves, test_debate_handles_critic_exception
from .test_ensemble_strategy import test_ensemble_strategy_default_vote, test_ensemble_strategy_with_custom_aggregator
from .test_group_chat_strategy import test_group_chat_rounds_and_done_flag
from .test_interaction_agent import DummyBackend, test_run_returns_serialized_result, test_run_raises_when_request_invalid
from .test_models import test_agent_definition_defaults_are_empty, test_orchestration_request_builds_context_and_metadata, test_agent_result_can_be_truthy_with_correct_fields, test_orchestration_request_requires_agents
from .test_native_interaction_backend import DummyOutput, DummyRegistry2, DummyMessageBus, make_task, make_request, test_pipeline_strategy_updates_context_and_returns_success, test_round_robin_propagates_output_between_agents, test_selector_defaults_when_no_selected_agent, test_task_failure_marks_step_and_aggregates_failure_status
from .test_self_refine_strategy import test_self_refine_converges_before_max, test_self_refine_handles_refinement_loop
