# engines/document/writers/osdm_writers/airflow_dag_writer.py
"""
Apache Airflow DAG Writer – converts a StateMachineDocument into a Python Airflow DAG.
- Uses sm.timer_trigger for scheduling (written back as schedule_interval).
- Uses script bodies stored in state.do_actions to recreate the original operator assignments.
- Handles dynamic tasks (loops) by detecting iteration patterns in scripts.
"""

from __future__ import annotations
from pathlib import Path
from typing import Optional, List, Dict, cast
import re

from .base_osdm_writer import BaseOSDMWriter, OSDMWriteOptions
from ...osdm_models import (
    BaseOSDMDocument,
    StateMachineDocument,
    StateMachineModel,
    StateMachineRegion,
    State,
    StateTransition,
    Script,
    TimerEventDefinition,
    TimerEventType,
)


class AirflowDAGWriter(BaseOSDMWriter):
    """Serialises a StateMachineDocument to Airflow DAG Python files."""

    name = "airflow_dag"
    supported_extensions = (".py",)

    def __init__(self, options: Optional[OSDMWriteOptions] = None):
        super().__init__(options)

    async def _write_design(self, base_document: BaseOSDMDocument) -> bytes:
        document = cast(StateMachineDocument, base_document)
        lines: List[str] = []
        self._write_header(document, lines)

        if not document.state_machines:
            lines.append("# No state machine defined.")
            return "\n".join(lines).encode(self.options.encoding or "utf-8")

        for sm in document.state_machines:
            self._write_dag_definition(lines, sm)

        source = "\n".join(lines) + "\n"
        return source.encode(self.options.encoding or "utf-8")

    def get_supported_media_types(self) -> list[str]:
        return ["text/x-python"]

    def get_supported_extensions(self) -> list[str]:
        return list(self.supported_extensions)

    # ── Header / imports ───────────────────────────────────────────
    def _write_header(self, doc: StateMachineDocument, lines: List[str]) -> None:
        lines.append("# Generated by OSDM Airflow Writer")
        lines.append(f"# Version: {doc.version}")
        if doc.source_file:
            lines.append(f"# Source: {doc.source_file}")
        lines.append("")
        lines.append("from airflow import DAG")
        lines.append("from airflow.operators.python import PythonOperator")
        lines.append("from datetime import datetime, timedelta")
        lines.append("")
        lines.append("")

    # ── DAG definition from a single StateMachineModel ──────────────
    def _write_dag_definition(self, lines: List[str], sm: StateMachineModel) -> None:
        dag_id = sm.id
        dag_name = sm.name or dag_id

        # Schedule from timer_trigger
        schedule_interval = "@daily"
        start_date = "datetime(2023, 1, 1)"
        if sm.timer_trigger:
            if sm.timer_trigger.timer_type == TimerEventType.CYCLE and sm.timer_trigger.time_cycle:
                schedule_interval = sm.timer_trigger.time_cycle.body or "@daily"
            elif sm.timer_trigger.time_duration:
                schedule_interval = sm.timer_trigger.time_duration.body or "@daily"
        if sm.start_date:
            start_date = f"datetime.fromisoformat('{sm.start_date}')"

        catchup = "False"

        lines.append(f"default_args = {{")
        lines.append(f"    'start_date': {start_date},")
        lines.append(f"    'retries': 1,")
        lines.append(f"}}")
        lines.append("")
        lines.append(f"with DAG(")
        lines.append(f"    dag_id='{dag_id}',")
        lines.append(f"    default_args=default_args,")
        lines.append(f"    schedule_interval={schedule_interval},")
        lines.append(f"    catchup={catchup},")
        lines.append(f") as dag:")
        indent = "    "

        # Collect all states recursively from the top region
        all_states: List[State] = []
        self._collect_states(sm.top_region, all_states)

        # Map state id to Airflow task id (Python variable name)
        task_var_map: Dict[str, str] = {}
        for state in all_states:
            task_id = state.id
            var_name = f"task_{task_id}"
            task_var_map[task_id] = var_name

            # The first script is the raw assignment (e.g., "task1 = PythonOperator(...)")
            scripts = [s for s in state.do_actions if isinstance(s, Script)]
            raw_script = scripts[0] if scripts else None
            callable_script = scripts[1] if len(scripts) > 1 else None

            if raw_script:
                if self._is_dynamic(state):
                    iter_source = self._iteration_source(state)
                    func_name = f"_task_{task_id}"
                    # If we have a callable body, write it as the function
                    func_body = callable_script.script_body if callable_script else "pass"
                    self._write_function(lines, func_name, func_body)
                    lines.append(f"{indent}for i in {iter_source}:")
                    lines.append(f"{indent}    task_{task_id}_{{i}} = PythonOperator(")
                    lines.append(f"{indent}        task_id=f'{task_id}_{{i}}',")
                    lines.append(f"{indent}        python_callable={func_name},")
                    lines.append(f"{indent}        dag=dag,")
                    lines.append(f"{indent}    )")
                else:
                    # Emit the raw assignment as-is for complete round‑trip
                    lines.append(f"{indent}{raw_script.script_body}")
            else:
                # No script – fallback
                lines.append(f"{indent}{var_name} = PythonOperator(task_id='{task_id}', python_callable=default_task_func, dag=dag)")

        # Dependencies
        for transition in self._collect_transitions(sm.top_region):
            if transition.source and transition.target:
                src_var = task_var_map.get(transition.source.id)
                tgt_var = task_var_map.get(transition.target.id)
                if src_var and tgt_var:
                    lines.append(f"{indent}{src_var} >> {tgt_var}")

        lines.append("")   # end with DAG block

    # ── Utility helpers ────────────────────────────────────────────
    def _collect_states(self, region, all_states: List[State]):
        for state in region.states:
            all_states.append(state)
            for sub_region in state.regions:
                self._collect_states(sub_region, all_states)

    def _collect_transitions(self, region) -> List[StateTransition]:
        transitions = []
        transitions.extend(region.transitions)
        for state in region.states:
            for sub_region in state.regions:
                transitions.extend(self._collect_transitions(sub_region))
            transitions.extend(state.outgoing_transitions)
        return transitions

    def _extract_script(self, state: State) -> Optional[Script]:
        """Return the first script found in the state's actions."""
        for actions in (state.entry_actions, state.do_actions, state.exit_actions):
            for action in actions:
                if isinstance(action, Script):
                    return action
        return None

    def _is_dynamic(self, state: State) -> bool:
        """Heuristic: if any do_action script contains 'for' or 'while', treat as dynamic."""
        script = self._extract_script(state)
        if script and (" for " in script.script_body or " while " in script.script_body):
            return True
        return False

    def _iteration_source(self, state: State) -> str:
        """Guess the iteration source from the script (simple approach)."""
        script = self._extract_script(state)
        if script:
            match = re.search(r'for\s+(\w+)\s+in\s+(\(?\w+[,\)\w]*)', script.script_body)
            if match:
                return match.group(2)
        return "range(10)"  # default

    def _write_function(self, lines: List[str], func_name: str, body: str) -> None:
        """Write a top-level Python function that Airflow tasks can call."""
        lines.append(f"def {func_name}(**kwargs):")
        for b_line in body.splitlines():
            lines.append(f"    {b_line}")