# engines/document/writers/osdm_writers/prefect_dag_writer.py
"""
Prefect DAG Writer – converts an OSDM StateMachineModel (unified) into a
Prefect 2.x Python flow file (.py).

Each State with a script in `do_actions` becomes a Prefect `@task`.
StateTransitions define data dependencies between tasks.
Scheduling is stored as annotations on the StateMachineModel:
  - schedule_cron (cron expression)
  - schedule_interval (timedelta seconds)
  - flow_name (override for the Prefect flow name)
Dynamic tasks are inferred from States with iteration scripts.
"""

from __future__ import annotations
from pathlib import Path
from typing import Optional, Dict, Any, List, cast
import re

from .base_osdm_writer import BaseOSDMWriter, OSDMWriteOptions
from ...models.osdm_models import (
    BaseOSDMDocument, StateMachineDocument,
    StateMachineModel,
    StateMachineRegion,
    State,
    StateTransition,
    Script,
)
from ...models.base import BaseDocument


class PrefectDAGWriter(BaseOSDMWriter):
    """Serialises an OSDM state machine to a Prefect 2.x flow Python file."""

    name = "prefect_dag"
    supported_extensions = (".py",)

    def __init__(self, options: Optional[OSDMWriteOptions] = None):
        super().__init__(options)

    async def _write_design(self, base_document: BaseOSDMDocument) -> bytes:
        document = cast(StateMachineDocument, base_document)
        lines: List[str] = []
        self._write_header(document, lines)

        if not document or not document.state_machines:
            lines.append("# No state machine defined.")
            return "\n".join(lines).encode(self.options.encoding or "utf-8")

        for sm in document.state_machines:
            self._write_flow_definition(lines, sm, document)

        source = "\n".join(lines) + "\n"
        return source.encode(self.options.encoding or "utf-8")

    def get_supported_media_types(self) -> list[str]:
        return ["text/x-python"]

    def get_supported_extensions(self) -> list[str]:
        return list(self.supported_extensions)

    # ── Header / imports ───────────────────────────────────────────
    def _write_header(self, doc: StateMachineDocument, lines: List[str]) -> None:
        lines.append("# Generated by OSDM Prefect Writer")
        lines.append(f"# Version: {doc.version}")
        if doc.source_file:
            lines.append(f"# Source: {doc.source_file}")
        lines.append("")
        lines.append("from prefect import flow, task")
        lines.append("from datetime import timedelta")
        lines.append("")
        lines.append("")

    # ── Flow definition ────────────────────────────────────────────
    def _write_flow_definition(self, lines: List[str], sm: StateMachineModel,
                               document: StateMachineDocument) -> None:
        flow_name = sm.name or sm.id

        # Use annotation for flow name if present
        for ann in getattr(sm, 'annotations', []):
            if ann.key == "flow_name":
                flow_name = ann.value
                break

        # Collect all states and transitions
        all_states: List[State] = []
        self._collect_states(sm.top_region, all_states)
        all_transitions: List[StateTransition] = []
        self._collect_transitions(sm.top_region, all_transitions)

        # Write each state as a @task if it has a script
        task_funcs: Dict[str, str] = {}  # state.id -> function name
        for state in all_states:
            script = self._extract_script(state)
            if script:
                func_name = f"_task_{state.id}"
                self._write_task(lines, func_name, script.script_body)
                task_funcs[state.id] = func_name

        # Build flow function
        lines.append("@flow(name=" + f'"{flow_name}")')
        lines.append(f"def flow_{flow_name.replace('-', '_')}():")
        indent = "    "

        # Determine what to pass between tasks based on transitions
        # In Prefect, you can call one task from another, and the result is passed as input.
        # We'll create a simple topological ordering: tasks with no incoming edges are called first.
        # Tasks with incoming edges receive the output of their predecessor.

        # For simplicity, we'll call tasks in an order that satisfies dependencies.
        called = set()
        # Start with initial states (those without incoming transitions or marked as initial)
        initial_states = self._find_initial_states(sm, all_states, all_transitions)

        for state in initial_states:
            if state.id in task_funcs:
                lines.append(f"{indent}{task_funcs[state.id]}_result = {task_funcs[state.id]}()")
            called.add(state.id)

        # Recursively call successor tasks
        queue = list(initial_states)
        while queue:
            current = queue.pop(0)
            for trans in all_transitions:
                if trans.source and trans.source.id == current.id and trans.target.id not in called:
                    target_id = trans.target.id
                    if target_id in task_funcs:
                        lines.append(f"{indent}{task_funcs[target_id]}_result = {task_funcs[target_id]}({task_funcs[current.id]}_result)")
                    called.add(target_id)
                    queue.append(trans.target)

        # Any remaining tasks that were not called (should not happen in a connected graph)
        for state in all_states:
            if state.id in task_funcs and state.id not in called:
                lines.append(f"{indent}{task_funcs[state.id]}_result = {task_funcs[state.id]}()")

        lines.append("")
        # Tell user how to run the flow
        lines.append(f"if __name__ == '__main__':")
        lines.append(f"    flow_{flow_name.replace('-', '_')}()")
        lines.append("")

    # ── Task function ──────────────────────────────────────────────
    def _write_task(self, lines: List[str], func_name: str, body: str) -> None:
        lines.append("@task")
        lines.append(f"def {func_name}(input_data=None):")
        for b_line in body.splitlines():
            lines.append(f"    {b_line}")
        # If the script doesn't explicitly return, add a default return
        if "return" not in body:
            lines.append("    return input_data")
        lines.append("")

    # ── Helpers ────────────────────────────────────────────────────
    def _collect_states(self, region: StateMachineRegion, all_states: List[State]) -> None:
        for state in region.states:
            all_states.append(state)
            for sub_region in state.regions:
                self._collect_states(sub_region, all_states)

    def _collect_transitions(self, region: StateMachineRegion,
                             all_transitions: List[StateTransition]) -> None:
        all_transitions.extend(region.transitions)
        for state in region.states:
            all_transitions.extend(state.outgoing_transitions)
            for sub_region in state.regions:
                self._collect_transitions(sub_region, all_transitions)

    def _extract_script(self, state: State) -> Optional[Script]:
        """Return the first script found in do_actions or entry_actions."""
        for actions in (state.do_actions, state.entry_actions):
            for action in actions:
                if isinstance(action, Script):
                    return action
        return None

    def _find_initial_states(self, sm: StateMachineModel, all_states: List[State],
                             all_transitions: List[StateTransition]) -> List[State]:
        """Return states that have no incoming transitions, or the top‑region initial state."""
        has_incoming = set()
        for trans in all_transitions:
            if trans.target:
                has_incoming.add(trans.target.id)
        initial = [s for s in all_states if s.id not in has_incoming]
        if not initial and sm.top_region.initial_state:
            initial = [sm.top_region.initial_state]
        if not initial and all_states:
            initial = [all_states[0]]
        return initial