# engines/document/models/msdm_registry.py

# Registry populated at module level
from typing import Dict
from .media_types import DocumentFormat
from .msdm_capabilities import (
    NestingDepth,
    MSDM_FormatCapability, 
    ConstraintCapability,
    InheritanceSupport,
    AnnotationSupport,
    ScalarSupport,
    CompositeSupport,
    TimeSeriesSupport,
    NamespaceSupport,
    EnumCapability,
    MSDM_FormatCapability,
    RelationshipModel,
    IndexCapability
)

MSDM_FORMAT_CAPABILITY_REGISTRY: Dict[DocumentFormat, MSDM_FormatCapability] = {}


def _reg(cap: MSDM_FormatCapability):
    MSDM_FORMAT_CAPABILITY_REGISTRY[cap.format] = cap


# ── JSON Schema ───────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.JSON_SCHEMA,
    description="JSON Schema",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE, ScalarSupport.TIMESTAMP],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.STRUCT,
                     CompositeSupport.REF, CompositeSupport.ENUM],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL,
                 ConstraintCapability.CHECK, ConstraintCapability.DEFAULT],
    indexes=[],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.KEY_VALUE,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.NONE,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=False,
    is_binary=False,
))

# ── XSD ───────────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.XSD,
    description="XML Schema Definition",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.LONG,
                  ScalarSupport.FLOAT, ScalarSupport.DOUBLE, ScalarSupport.DECIMAL,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE, ScalarSupport.TIME,
                  ScalarSupport.TIMESTAMP, ScalarSupport.BINARY],
    composite_types=[CompositeSupport.STRUCT, CompositeSupport.REF,
                     CompositeSupport.ENUM, CompositeSupport.UNION],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL,
                 ConstraintCapability.CHECK, ConstraintCapability.DEFAULT],
    indexes=[],
    inheritance=InheritanceSupport.SINGLE,
    relationship_model=RelationshipModel.FOREIGN_KEY,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.HIERARCHICAL,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=False,
    is_binary=False,
))

# ── SQL DDL ─────────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.SQL_DDL,
    description="SQL Data Definition Language",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.LONG,
                  ScalarSupport.FLOAT, ScalarSupport.DOUBLE, ScalarSupport.DECIMAL,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE, ScalarSupport.TIME,
                  ScalarSupport.TIMESTAMP, ScalarSupport.BINARY, ScalarSupport.JSON,
                  ScalarSupport.XML, ScalarSupport.UUID],
    composite_types=[CompositeSupport.ARRAY],  # limited array support in some dialects
    nesting_depth=NestingDepth.SINGLE_LEVEL,
    constraints=[ConstraintCapability.PRIMARY_KEY, ConstraintCapability.FOREIGN_KEY,
                 ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL,
                 ConstraintCapability.CHECK, ConstraintCapability.DEFAULT],
    indexes=[IndexCapability.UNIQUE_INDEX, IndexCapability.NON_UNIQUE_INDEX,
             IndexCapability.COMPOSITE_INDEX],
    inheritance=InheritanceSupport.SINGLE,
    relationship_model=RelationshipModel.FOREIGN_KEY,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.TIMESTAMP_FIELD,
    namespace=NamespaceSupport.FLAT,
    enum_support=EnumCapability.NONE,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── ERD ────────────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.ERD,
    description="Entity‑Relationship Diagram (generic)",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE],
    composite_types=[],
    nesting_depth=NestingDepth.NONE,
    constraints=[ConstraintCapability.PRIMARY_KEY, ConstraintCapability.FOREIGN_KEY,
                 ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL],
    indexes=[],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.EXPLICIT,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.NONE,
    enum_support=EnumCapability.NONE,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── UML XMI ────────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.UML_XMI,
    description="UML XMI Class Diagram",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE],
    composite_types=[CompositeSupport.STRUCT],
    nesting_depth=NestingDepth.SINGLE_LEVEL,
    constraints=[ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL],
    indexes=[],
    inheritance=InheritanceSupport.MULTIPLE,
    relationship_model=RelationshipModel.EXPLICIT,
    annotations=AnnotationSupport.KEY_VALUE,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.HIERARCHICAL,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── Protobuf ────────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.PROTOBUF,
    description="Protobuf IDL",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.LONG,
                  ScalarSupport.FLOAT, ScalarSupport.DOUBLE, ScalarSupport.BOOLEAN,
                  ScalarSupport.BINARY, ScalarSupport.UUID],   # UUID is not native, but via lib
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.STRUCT,
                     CompositeSupport.ENUM, CompositeSupport.MAP],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.DEFAULT],
    indexes=[],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.DIRECTIVES,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.FLAT,
    enum_support=EnumCapability.INT_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=True,
    is_binary=True,
))

# ── Avro Schema ─────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.AVRO_SCHEMA,
    description="Apache Avro Schema",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.LONG,
                  ScalarSupport.FLOAT, ScalarSupport.DOUBLE, ScalarSupport.BOOLEAN,
                  ScalarSupport.BINARY, ScalarSupport.UUID, ScalarSupport.DECIMAL,
                  ScalarSupport.DATE, ScalarSupport.TIME, ScalarSupport.TIMESTAMP],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.MAP,
                     CompositeSupport.STRUCT, CompositeSupport.ENUM,
                     CompositeSupport.UNION],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.DEFAULT],
    indexes=[],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.TIMESTAMP_FIELD,
    namespace=NamespaceSupport.FLAT,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=True,
    is_binary=True,
))

# ── Thrift IDL ───────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.THRIFT_IDL,
    description="Apache Thrift IDL",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.LONG,
                  ScalarSupport.FLOAT, ScalarSupport.DOUBLE, ScalarSupport.BOOLEAN,
                  ScalarSupport.BINARY],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.MAP,
                     CompositeSupport.STRUCT, CompositeSupport.ENUM,
                     CompositeSupport.UNION],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.DEFAULT],
    indexes=[],
    inheritance=InheritanceSupport.SINGLE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.FLAT,
    enum_support=EnumCapability.INT_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=True,
    is_binary=False,
))

# ── GraphQL Schema ───────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.GRAPHQL_SCHEMA,
    description="GraphQL Schema",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.UUID],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.STRUCT,
                     CompositeSupport.ENUM, CompositeSupport.UNION],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.NOT_NULL, ConstraintCapability.DEFAULT],
    indexes=[],
    inheritance=InheritanceSupport.MULTIPLE,
    relationship_model=RelationshipModel.NAVIGATION,
    annotations=AnnotationSupport.DIRECTIVES,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.NONE,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── OWL / RDF ────────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.OWL,
    description="Web Ontology Language (OWL)",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.BOOLEAN],
    composite_types=[CompositeSupport.STRUCT, CompositeSupport.REF,
                     CompositeSupport.ENUM],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL],
    indexes=[],
    inheritance=InheritanceSupport.MULTIPLE,
    relationship_model=RelationshipModel.NAVIGATION,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.HIERARCHICAL,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=False,
    is_binary=False,
))

# ── CUE ──────────────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.CUE,
    description="CUE Data Language",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.STRUCT,
                     CompositeSupport.ENUM, CompositeSupport.UNION],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.CHECK, ConstraintCapability.DEFAULT],
    indexes=[],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.NONE,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.FLAT,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=False,
    is_binary=False,
))

# ── CQL (Cassandra) ──────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.CQL,
    description="Cassandra Query Language Schema",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.LONG,
                  ScalarSupport.FLOAT, ScalarSupport.DOUBLE, ScalarSupport.BOOLEAN,
                  ScalarSupport.TIMESTAMP, ScalarSupport.UUID, ScalarSupport.BINARY],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.MAP, CompositeSupport.STRUCT],
    nesting_depth=NestingDepth.SINGLE_LEVEL,
    constraints=[ConstraintCapability.PRIMARY_KEY, ConstraintCapability.NOT_NULL,
                 ConstraintCapability.DEFAULT],
    indexes=[IndexCapability.NON_UNIQUE_INDEX, IndexCapability.COMPOSITE_INDEX],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.TIMESTAMP_FIELD,
    namespace=NamespaceSupport.FLAT,
    enum_support=EnumCapability.NONE,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── MongoDB Schema ───────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.MONGODB_SCHEMA,
    description="MongoDB Schema (Mongoose / Validator)",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.LONG,
                  ScalarSupport.FLOAT, ScalarSupport.DOUBLE, ScalarSupport.BOOLEAN,
                  ScalarSupport.DATE, ScalarSupport.TIMESTAMP, ScalarSupport.BINARY,
                  ScalarSupport.JSON],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.STRUCT, CompositeSupport.MAP],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL,
                 ConstraintCapability.DEFAULT],
    indexes=[IndexCapability.UNIQUE_INDEX, IndexCapability.NON_UNIQUE_INDEX,
             IndexCapability.COMPOSITE_INDEX],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.FOREIGN_KEY,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.NONE,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── InfluxDB Schema ─────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.INFLUXDB_SCHEMA,
    description="InfluxDB Measurement Schema",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.TIMESTAMP],
    composite_types=[],
    nesting_depth=NestingDepth.NONE,
    constraints=[ConstraintCapability.NOT_NULL],
    indexes=[],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.TIMESTAMP_FIELD | TimeSeriesSupport.TAG_FIELDS | TimeSeriesSupport.VALUE_FIELDS | TimeSeriesSupport.RETENTION_POLICY,
    namespace=NamespaceSupport.NONE,
    enum_support=EnumCapability.NONE,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── Elasticsearch Mapping ───────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.ELASTICSEARCH_MAPPING,
    description="Elasticsearch Index Mapping",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.LONG,
                  ScalarSupport.FLOAT, ScalarSupport.DOUBLE, ScalarSupport.BOOLEAN,
                  ScalarSupport.DATE, ScalarSupport.BINARY],
    composite_types=[CompositeSupport.STRUCT],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.NOT_NULL],
    indexes=[],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.NONE,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.NONE,
    enum_support=EnumCapability.NONE,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── Neo4j Schema ────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.NEO4J_SCHEMA,
    description="Neo4j Cypher Schema",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE, ScalarSupport.TIMESTAMP],
    composite_types=[CompositeSupport.ARRAY],
    nesting_depth=NestingDepth.SINGLE_LEVEL,
    constraints=[ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL],
    indexes=[IndexCapability.UNIQUE_INDEX, IndexCapability.COMPOSITE_INDEX],
    inheritance=InheritanceSupport.NONE,
    relationship_model=RelationshipModel.NAVIGATION,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.NONE,
    enum_support=EnumCapability.NONE,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── PlantUML ────────────────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.PLANTUML,
    description="PlantUML Diagram",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.BOOLEAN],
    composite_types=[],
    nesting_depth=NestingDepth.NONE,
    constraints=[ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL],
    indexes=[],
    inheritance=InheritanceSupport.MULTIPLE,
    relationship_model=RelationshipModel.EXPLICIT,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.NONE,
    enum_support=EnumCapability.STRING_ENUM,
    has_entity_concept=True,
    supports_reuse=False,
    supports_streaming=False,
    is_binary=False,
))

# ── Python Model (Pydantic / dataclass) ──────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.PYTHON_MODEL,
    description="Python Data Model (Pydantic, dataclass)",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE, ScalarSupport.TIME,
                  ScalarSupport.TIMESTAMP, ScalarSupport.BINARY, ScalarSupport.UUID,
                  ScalarSupport.JSON],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.MAP,
                     CompositeSupport.STRUCT, CompositeSupport.ENUM,
                     CompositeSupport.UNION, CompositeSupport.REF],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.UNIQUE, ConstraintCapability.NOT_NULL,
                 ConstraintCapability.CHECK, ConstraintCapability.DEFAULT],
    indexes=[],
    inheritance=InheritanceSupport.MULTIPLE,
    relationship_model=RelationshipModel.FOREIGN_KEY,
    annotations=AnnotationSupport.KEY_VALUE,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.HIERARCHICAL,
    enum_support=EnumCapability.STRING_ENUM | EnumCapability.INT_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=False,
    is_binary=False,
))

# ── TypeScript Interface ────────────────────────────────────────
_reg(MSDM_FormatCapability(
    format=DocumentFormat.TYPESCRIPT_INTERFACE,
    description="TypeScript Interface / Type Definition",
    scalar_types=[ScalarSupport.STRING, ScalarSupport.INT, ScalarSupport.FLOAT,
                  ScalarSupport.BOOLEAN, ScalarSupport.DATE, ScalarSupport.TIMESTAMP,
                  ScalarSupport.BINARY],
    composite_types=[CompositeSupport.ARRAY, CompositeSupport.MAP,
                     CompositeSupport.STRUCT, CompositeSupport.ENUM,
                     CompositeSupport.UNION],
    nesting_depth=NestingDepth.DEEP,
    constraints=[ConstraintCapability.NOT_NULL],
    indexes=[],
    inheritance=InheritanceSupport.MULTIPLE,
    relationship_model=RelationshipModel.NONE,
    annotations=AnnotationSupport.SIMPLE_COMMENT,
    time_series=TimeSeriesSupport.NONE,
    namespace=NamespaceSupport.HIERARCHICAL,
    enum_support=EnumCapability.STRING_ENUM | EnumCapability.INT_ENUM,
    has_entity_concept=True,
    supports_reuse=True,
    supports_streaming=False,
    is_binary=False,
))