# from pathlib import Path
# from typing import Any, BinaryIO, TextIO

# from engines.document.writers.base import BaseDocumentWriter, BaseDocument
# from engines.document.models.media_types import MEDIA_TYPES
# from engines.document.models.ksdm_models import SemanticGraphDocument


# class GqlWriter(BaseDocumentWriter):
#     supported_format = MEDIA_TYPES["gql_schema"]

#     def can_write(self, document) -> bool:
#         return isinstance(document, SemanticGraphDocument) and bool(getattr(document, 'gql_schemas', []))

#     async def write(self, document: BaseDocument, destination: str | Path | BinaryIO | TextIO | None = None, **options: Any) -> bytes:
#         schema = getattr(document, 'gql_schemas', [{}])[0] if getattr(document, 'gql_schemas', []) else {}
#         lines = []
#         lines.append('# GQL Schema (ISO/IEC 39075)')
#         lines.append('# Auto-generated by knowledge layer')
#         lines.append('')
#         for nt in schema.get('node_types', []):
#             lines.append(f'DEFINE NODE TYPE {nt.get("name", "Unknown")} {{')
#             for prop in nt.get('properties', []):
#                 req = 'REQUIRED' if prop.get('cardinality') == 'REQUIRED' else 'OPTIONAL'
#                 lines.append(f'  {prop.get("name", "prop")}: {prop.get("type_name", "STRING")} {req}')
#             lines.append('}')
#             lines.append('')
#         for et in schema.get('edge_types', []):
#             lines.append(f'DEFINE EDGE TYPE {et.get("name", "Unknown")} FROM {et.get("source", "")} TO {et.get("target", "")} {{')
#             for prop in et.get('properties', []):
#                 lines.append(f'  {prop.get("name", "prop")}: {prop.get("type_name", "STRING")}')
#             lines.append('}')
#             lines.append('')
#         output = '\n'.join(lines).encode('utf-8')
#         if destination is not None:
#             if isinstance(destination, (str, Path)):
#                 Path(destination).write_bytes(output)
#             else:
#                 destination.write(output.decode('utf-8'))  # type: ignore
#         return output
