# engines/document/writers/ssdm_writers/cddl_writer.py
"""
CDDL (CBOR Data Definition Language) Writer – serialises an SSDM_DOCUMENT
into a CDDL text file (.cddl).

The writer maps operations and their MSDM‑described inputs/outputs into CDDL
rules, preserving the type structure without using annotations.
"""

from __future__ import annotations
from pathlib import Path
from typing import Optional, List, Dict, cast

from .base_ssdm_writer import BaseSSDMWriter, SSDMWriteOptions
from ...models.ssdm_models import (
    SSDM_DOCUMENT,
    Operation,
    Parameter,
    RequestBody,
    Response,
)
from ...models.msdm_models import (
    MSDMDocument,
    Entity,
    Attribute,
    DataType,
    ScalarType,
)
from ...models.base import BaseDocument


class CDDLWriter(BaseSSDMWriter):
    """Serialises an SSDM_DOCUMENT to CDDL format."""

    name = "cddl"
    supported_extensions = (".cddl",)

    _cddl_type_map = {
        ScalarType.STRING: "text",
        ScalarType.INT: "int",
        ScalarType.LONG: "int",
        ScalarType.FLOAT: "float16",
        ScalarType.DOUBLE: "float32",
        ScalarType.BOOLEAN: "bool",
        ScalarType.BINARY: "bytes",
        ScalarType.DATE: "text",        # CDDL has no native date
        ScalarType.TIME: "text",
        ScalarType.TIMESTAMP: "text",
        ScalarType.DURATION: "text",
        ScalarType.UUID: "text",
        ScalarType.DECIMAL: "text",
        ScalarType.ANY: "any",
    }

    def __init__(self, options: Optional[SSDMWriteOptions] = None):
        super().__init__(options)

    async def _write_design(self, document: SSDM_DOCUMENT) -> bytes:
        lines: List[str] = []
        lines.append("; Generated by SSDM CDDL Writer")
        lines.append("")
        lines.append(f"start = {self._safe_rule_name(document.title or 'service')}")
        lines.append("")

        # Write reusable type definitions from MSDM
        if document.type_definitions:
            for entity in document.type_definitions.entities:
                self._write_entity(lines, entity)

        # Write operation‑specific rules
        for op in document.operations:
            self._write_operation(lines, op)

        return "\n".join(lines).encode(self.options.encoding or "utf-8")

    def get_supported_media_types(self) -> list[str]:
        return ["text/plain"]

    def get_supported_extensions(self) -> list[str]:
        return list(self.supported_extensions)

    # ── Entity → CDDL group rule ──────────────────────────────────
    def _write_entity(self, lines: List[str], entity: Entity) -> None:
        rule_name = self._safe_rule_name(entity.name)
        lines.append(f"{rule_name} = {{")
        for attr in entity.attributes:
            type_str = self._datatype_to_cddl(attr.data_type)
            if not attr.required:
                lines.append(f"  ? {attr.name}: {type_str}")
            else:
                lines.append(f"  {attr.name}: {type_str}")
        lines.append("}")
        lines.append("")

    # ── Operation → CDDL rules for request/response ──────────────
    def _write_operation(self, lines: List[str], op: Operation) -> None:
        op_name = self._safe_rule_name(op.name)

        # Request rule (combining parameters + body into one group)
        req_rule = f"{op_name}_Request"
        lines.append(f"{req_rule} = {{")
        for param in op.parameters:
            p_type = self._param_type_cddl(param)
            lines.append(f"  {param.name}: {p_type}")
        if op.request_body and op.request_body.content_entity:
            body_type = self._safe_rule_name(op.request_body.content_entity.name)
            lines.append(f"  body: {body_type}")
        elif op.request_body:
            lines.append(f"  body: any")
        lines.append("}")
        lines.append("")

        # Response rule(s)
        for resp in op.responses:
            resp_rule = f"{op_name}_Response_{resp.status_code}"
            lines.append(f"{resp_rule} = {{")
            if resp.content_entity:
                resp_type = self._safe_rule_name(resp.content_entity.name)
                lines.append(f"  body: {resp_type}")
            else:
                lines.append(f"  ; empty response")
            lines.append("}")
            lines.append("")

    # ── DataType → CDDL type string ──────────────────────────────
    def _datatype_to_cddl(self, dt: DataType) -> str:
        base = dt.base
        if base == ScalarType.ARRAY:
            elem = self._datatype_to_cddl(dt.element_type) if dt.element_type else "any"
            return f"[* {elem}]"
        if base == ScalarType.MAP:
            key = self._datatype_to_cddl(dt.key_type) if dt.key_type else "text"
            val = self._datatype_to_cddl(dt.value_type) if dt.value_type else "any"
            return f"{{* {key} => {val}}}"
        if base == ScalarType.REF:
            return self._safe_rule_name(dt.ref_entity or "unknown")
        if base == ScalarType.STRUCT:
            return "any"   # should be a reference to an entity; fallback
        return self._cddl_type_map.get(base, "any")

    def _param_type_cddl(self, param: Parameter) -> str:
        if param.type_entity:
            return self._safe_rule_name(param.type_entity.name)
        if param.type_string:
            return param.type_string
        return "any"

    @staticmethod
    def _safe_rule_name(name: str) -> str:
        """Replace characters not allowed in CDDL identifiers."""
        import re
        return re.sub(r'[^a-zA-Z0-9_]', '_', name or "unnamed")